### ISSUE TITLE
1.10 not triggering sheet workers even though toggle is on

### ISSUE THREAD

**Issue by AsylumOfMind** [Roll20/roll20-api-scripts#1676]
I have tried disable/enable script and refreshing page several times in several combinations, but can't get it to work.

I don't think it is my `on('change:` because if I manually change 'base_level' it triggers, but if I `!setattr --sel --base_level|2` it changes the base_level to 2, but doesn't trigger the sheet worker.

**Comment by AsylumOfMind** [comment]
Adding to this. Not sure if this is a cause. I have "Latest" selected as my version and have tried resetting the API sandbox. I only have chatSetAttr enabled and this is the output I get in the Mod Output Console only when chatSetAttr is enabled.
```
"-=> ChatSetAttr v1.10 <=-"
"SyntaxError: Unexpected token ';'"
"SyntaxError: Unexpected token ';'
    at eval (<anonymous>)
    at messageHandler (evalmachine.<anonymous>:713:6)
    at process.<anonymous> (/home/node/d20-api-server/node_modules/tiny-worker/lib/worker.js:65:55)
    at process.emit (events.js:314:20)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)"
```
