### ISSUE TITLE
2.3 Error on !flip

### ISSUE THREAD

**Issue by Sral92x** [Roll20/roll20-api-scripts#297]
TypeError: msg.content.trim(...).splitArgs is not a function
TypeError: msg.content.trim(...).splitArgs is not a function
    at handleInput (apiscript.js:39:39)
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:105:34), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:105:34), <anonymous>:70:8)
    at /home/node/d20-api-server/api.js:1197:12
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)
    at Kd (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:546)
    at Id.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:489)
    at Ld.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:94:425)
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:111:400

**Comment by RyanNerd** [comment]
This issue appears to be fixed in the latest version. The `splitArgs` dependency is listed in the `script.json` file.
