### ISSUE TITLE
PCGenPFImport API Output Console First argument contains undefined in property 'name'

### ISSUE THREAD

**Issue by earthquake13** [Roll20/roll20-api-scripts#726]
For reference, the error message generated was: Error: Firebase.set failed: First argument contains undefined in property 'name'
Error: Firebase.set failed: First argument contains undefined in property 'name'
    at Ba (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:9:49)
    at Ba (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:10:207)
    at Aa (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:8:462)
    at J.set (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:146:98)
    at createObj (/home/node/d20-api-server/api.js:2703:26)
    at apiscript.js:126:27
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:151:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:151:1), <anonymous>:70:8)
    at /home/node/d20-api-server/api.js:1634:12
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560

**Comment by achugb** [comment]
Just submitted a pull request that addresses this: https://github.com/Roll20/roll20-api-scripts/pull/776
